// src/components/home/MobileApp.tsx
'use client';
import React from 'react';
import NextImg from '../common/next-img';
import Link from 'next/link';

type Props = {
  data: any;
};

const MobileApp = ({ data }: Props) => {
  return (
    <>
      {/* section 5 */}
      <div className="mb-10 bg-[#0F1B0E] pt-10 lg:mb-[60px] lg2:pt-16 xl:mb-20 2xl:mb-[100px] 2xl:pt-[74px] 3xl:mb-[160px]">
        <div className="custom-container">
          <div className="flex flex-col md:grid md:grid-cols-2 md:gap-10 lg:gap-0 lg2:px-[107px] 3xl:px-[128px]">
            <div
              className="flex flex-col gap-5 md:my-auto lg:gap-8"
              data-aos="fade-up"
              data-aos-delay="100"
            >
              <div className="flex flex-col gap-1">
                <div className="relative h-[32px] w-[73px] lg:h-[48px] lg:w-[111px]">
                  <NextImg
                    src="/assets/icons/Logo-small.svg"
                    alt="Capi"
                    objectFit="cover"
                    className="object-top"
                  />
                </div>
                <span className="text-sm font-medium leading-[28px] text-[#02E56A] lg:text-[18px]">
                  Mobile App
                </span>
              </div>
              <h3 className="text-[20px] font-bold text-[#FFF] lg:w-[80%] lg:text-[40px] lg:leading-[46px] lg2:w-[75%] lg2:text-[56px] lg2:leading-[58px] 2xl:text-[58px] 3xl:text-[60px] 3xl:leading-[60px]">
                {data.titles[0].title}{' '}
                <span className="text-[#02E56A]">{data.titles[1].title} </span>
                {data.titles[2].title}
              </h3>
              <p className="text-[14px] font-medium text-[#8C9AA4] lg:w-[80%] lg:text-base lg:leading-[24px] lg2:text-[18px] lg2:leading-[28px]">
                {data.description}
              </p>
              <div className="flex flex-wrap items-center gap-3">
                <Link
                  href={data.ctas.gg_play}
                  className="flex cursor-pointer items-center gap-[9px] rounded-[9px] bg-[#111] p-[10px] pr-8 md:pr-6 lg:pr-[50px]"
                >
                  <div className="relative h-6 w-6">
                    <NextImg
                      src="/assets/icons/google-play1.svg"
                      alt="Capi"
                      objectFit="cover"
                    />
                  </div>
                  <div className="flex flex-col">
                    <span className="text-xs font-medium uppercase leading-normal text-[rgba(255,255,255,0.79)]">
                      Get it on
                    </span>
                    <span className="text-[14px] font-semibold leading-[21px] text-[#FFF] lg:text-base">
                      Google Play
                    </span>
                  </div>
                </Link>
                <Link
                  href={data.ctas.app_store}
                  className="flex cursor-pointer items-center gap-[9px] rounded-[9px] bg-[#111] p-[10px] pr-6"
                >
                  <div className="relative h-6 w-6">
                    <NextImg
                      src="/assets/icons/apple-logo1.svg"
                      alt="Capi"
                      objectFit="cover"
                    />
                  </div>
                  <div className="flex flex-col">
                    <span className="text-xs font-medium uppercase leading-normal text-[rgba(255,255,255,0.79)]">
                      Download on the
                    </span>
                    <span className="text-[14px] font-semibold leading-[21px] text-[#FFF] lg:text-base">
                      App Store
                    </span>
                  </div>
                </Link>
              </div>
            </div>
            <div
              className="relative mt-10 h-[390px] w-full sm:h-[470px] md:pt-[141%] lg:mt-0"
              data-aos="fade-up"
              data-aos-delay="400"
            >
              <NextImg
                src={process.env.REACT_APP_IMG_URL + data.cover}
                alt="Capi"
                objectFit="contain"
              />
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default MobileApp;

// pages/nen-tang-cong-nghe/components/mobile-app.vue
<template>
  <section class="animate-ups container-nen-tang">
    <div
      class="bg-[#1D1D1F] rounded-[16px] lg:rounded-[24px] xl:rounded-[32px] xxl:rounded-[40px] w-full h-[640px] md:h-[360px] lg:h-[460px] xl:h-[520px] 2xl:h-[550px] xxl:h-[580px] 4xl:h-[600px] p-[20px_20px_0] md:p-[30px_40px_0_24px] lg:p-[39px_52px_0_30px] xl:p-[48px_60px_0_40px] 2xl:p-[63px_70px_0_50px] xxl:p-[80px_60px_0] 4xl:p-[60px_90px_0_70px] overflow-hidden"
    >
      <div
        class="flex flex-col md:flex-row items-end gap-[57px] md:gap-[44px] lg:gap-[69px] xl:gap-[63px] 2xl:gap-[43px] xxl:gap-[130px] 4xl:gap-[103px] h-full"
      >
        <div class="flex-1 md:pb-[60px] flex flex-col gap-6 lg:gap-[36px]">
          <div class="space-y-3 xl:space-y-4">
            <div
              class="text-white text-xl lg:text-[30px] xl:text-[40px] font-bold lg:leading-[1.3] 4xl:leading-[1.4]"
            >
              Hơn cả một <br />
              trải nghiệm đầu tư
            </div>
            <div class="text-[#B3B3B3] text-sm xl:text-lg font-medium">
              Tăng tốc giao dịch nhanh chóng với ứng dụng di động cá nhân hoá
              riêng cho bạn.
            </div>
          </div>

          <div class="flex flex-col gap-3">
            <button
              class="w-[180px] bg-[#111] rounded-[9px] flex gap-[9px] p-[6px_10px] items-center"
            >
              <div class="relative size-6">
                <nuxt-img
                  src="icons/google-play-1.svg"
                  loading="lazy"
                  alt="UPS"
                  class="object-cover size-full"
                />
              </div>
              <div>
                <div
                  class="uppercase text-xs font-medium text-[rgba(255,255,255,0.57)] text-start"
                >
                  get it on
                </div>
                <div class="text-white font-base font-semibold text-start">
                  Google Play
                </div>
              </div>
            </button>

            <button
              class="w-[180px] bg-[#111] rounded-[9px] flex gap-[9px] p-[6px_10px] items-center"
            >
              <div class="relative size-6">
                <nuxt-img
                  src="icons/apple-logo-1.svg"
                  loading="lazy"
                  alt="UPS"
                  class="object-cover size-full"
                />
              </div>
              <div>
                <div
                  class="uppercase text-xs font-medium text-[rgba(255,255,255,0.57)] text-start"
                >
                  Download on the
                </div>
                <div class="text-white font-base font-semibold text-start">
                  App Store
                </div>
              </div>
            </button>
          </div>
        </div>

        <div
          class="relative w-full md:w-[320px] lg:w-[460px] xl:w-[516px] xxl:w-[570px] 4xl:w-[578px] h-full"
        >
          <nuxt-img
            src="images/nen-tang-4.png"
            loading="lazy"
            alt="UPS"
            class="object-contain absolute top-0 left-1/2 -translate-x-1/2 md:-translate-x-0 md:left-0 w-[296px] md:w-full h-[384px] md:h-[506px] lg:h-[660px] xl:h-[713px] 2xl:h-[698px] xxl:h-[755px]"
          />
        </div>
      </div>
    </div>
  </section>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { cn } from "~/lib/utils";

export default defineComponent({
  name: "MobileApp",
  components: {},
  setup(props, ctx) {
    return {
      cn,
    };
  },
});
</script>

<style scoped></style>
