// components/common/the-footer/index.vue
<template>
	<footer id="footer">
		<div class="bg-[#04C95F]">
			<div class="container">
				<div
					class="flex gap-10 xl:gap-0 flex-col xl:flex-row justify-between py-10 lg:pt-12 xl:pt-20 lg:pb-20 xl:pb-[100px]"
				>
					<div class="">
						<div
							class="inline-flex w-[256px] h-[64px] lg:w-[300px] lg:h-[74px] xl:w-[409px] xl:h-[94px] relative"
						>
							<nuxt-img
								format="webp"
								loading="lazy"
								quality="80"
								src="/logo/logo-full-light.png"
								width="409"
								height="94"
								alt="UPS"
								class="absolute w-full h-full object-contain"
							/>
						</div>

						<div class="flex justify-between">
							<div class="flex flex-col">
								<div class="w-full max-w-[405px] flex flex-col gap-4 mt-6 xl:mt-10">
									<nuxt-link
										href="/"
										class="flex flex-col gap-4"
									>
										<nuxt-img
											format="webp"
											src="/logo/logo-row-light.png"
											alt="UPS"
											width="20"
											height="20"
										/>
										<span class="text-base xl:text-lg text-[#15171E] font-bold">
											Tầng 8 - Tòa nhà Hapro, Số 11B Cát Linh, Phường Quốc Tử Giám, Quận Đống Đa,
											Hà Nội
										</span>
									</nuxt-link>
									<nuxt-link
										href="tel:1800.0967"
										class="flex gap-4"
									>
										<!-- <div class="w-5 h-5"></div> -->
										<span class="text-base xl:text-lg text-[#15171E] font-bold"> 1800.0967 </span>
									</nuxt-link>
									<nuxt-link
										href="mailto:support@upsecurities.vn"
										class="flex gap-4"
									>
										<!-- <div class="w-5 h-5"></div> -->
										<span class="text-base xl:text-lg text-[#15171E] font-bold">
											support@upsecurities.vn
										</span>
									</nuxt-link>
								</div>
							</div>
						</div>

						<!-- SOSIAL -->
						<div class="mt-4 flex gap-2">
							<nuxt-link
								href="/"
								target="_blank"
								class="inline-flex items-center justify-center relative w-6 h-6"
							>
								<nuxt-img
									format="webp"
									loading="lazy"
									alt="Facebook"
									height="24"
									src="/social/facebook.svg"
									class="absolute w-full h-full object-contain"
								/>
							</nuxt-link>
							<nuxt-link
								href="/"
								target="_blank"
								class="inline-flex items-center justify-center relative w-6 h-6"
							>
								<nuxt-img
									format="webp"
									loading="lazy"
									alt="instagram"
									height="24"
									src="/social/instagram.svg"
									class="absolute w-full h-full object-contain"
								/>
							</nuxt-link>
							<nuxt-link
								href="/"
								target="_blank"
								class="inline-flex items-center justify-center relative w-6 h-6"
							>
								<nuxt-img
									format="webp"
									loading="lazy"
									alt="Twitter"
									height="24"
									src="/social/twitter.svg"
									class="absolute w-full h-full object-contain"
								/>
							</nuxt-link>
							<nuxt-link
								href="/"
								target="_blank"
								class="inline-flex items-center justify-center relative w-6 h-6"
							>
								<nuxt-img
									format="webp"
									loading="lazy"
									alt="Tiktok"
									height="24"
									src="/social/tiktok.svg"
									class="absolute w-full h-full object-contain"
								/>
							</nuxt-link>
							<nuxt-link
								href="/"
								target="_blank"
								class="inline-flex items-center justify-center relative w-6 h-6"
							>
								<nuxt-img
									format="webp"
									loading="lazy"
									alt="Telegram"
									height="24"
									src="/social/telegram.svg"
									class="absolute w-full h-full object-contain"
								/>
							</nuxt-link>
							<nuxt-link
								href="/"
								target="_blank"
								class="inline-flex items-center justify-center relative w-6 h-6"
							>
								<nuxt-img
									format="webp"
									loading="lazy"
									alt="In"
									height="24"
									src="/social/in.svg"
									class="absolute w-full h-full object-contain"
								/>
							</nuxt-link>
						</div>
					</div>

					<div class="w-full xl:w-[800px] max-w-full">
						<div class="flex flex-col lg:flex-row gap-10">
							<div class="w-max">
								<h4 class="text-base xl:text-lg text-[#000] font-bold">Khách hàng cá nhân</h4>

								<div class="mt-4 xl:mt-6 flex gap-3 flex-col">
									<nuxt-link
										to="/"
										class="text-sm xl:text-base text-[#000] font-medium"
									>
										Cổ phiếu
									</nuxt-link>
									<nuxt-link
										to="/"
										class="text-sm xl:text-base text-[#000] font-medium"
									>
										Trái phiếu
									</nuxt-link>
									<nuxt-link
										to="/"
										class="text-sm xl:text-base text-[#000] font-medium"
									>
										Phái sinh
									</nuxt-link>
									<nuxt-link
										to="/"
										class="text-sm xl:text-base text-[#000] font-medium"
									>
										Biểu phí giao dịch
									</nuxt-link>
									<nuxt-link
										to="/"
										class="text-sm xl:text-base text-[#000] font-medium"
									>
										Sản phẩm tài chính
									</nuxt-link>
								</div>
							</div>
							<div class="w-max">
								<h4 class="text-base lg:text-lg text-[#000] font-bold">Khách hàng doanh nghiệp</h4>

								<div class="mt-4 xl:mt-6 flex gap-3 flex-col">
									<nuxt-link
										to="/"
										class="text-sm xl:text-base text-[#000] font-medium"
									>
										Tư vấn tài chính
									</nuxt-link>
									<nuxt-link
										to="/"
										class="text-sm xl:text-base text-[#000] font-medium"
									>
										Tin đấu giá
									</nuxt-link>
								</div>
							</div>
							<div class="w-max">
								<h4 class="text-base xl:text-lg text-[#000] font-bold">Đầu tư cùng UPS</h4>

								<div class="mt-4 xl:mt-6 flex gap-3 flex-col">
									<nuxt-link
										to="/"
										class="text-sm xl:text-base text-[#000] font-medium"
									>
										Nhận định thị trường
									</nuxt-link>
									<nuxt-link
										to="/"
										class="text-sm xl:text-base text-[#000] font-medium"
									>
										Cộng đồng
									</nuxt-link>
									<nuxt-link
										to="/"
										class="text-sm xl:text-base text-[#000] font-medium"
									>
										Cẩm nang đầu tư
									</nuxt-link>
								</div>
							</div>
							<div class="w-max">
								<h4 class="text-base xl:text-lg text-[#000] font-bold">Về UPS</h4>

								<div class="mt-4 xl:mt-6 flex gap-3 flex-col">
									<nuxt-link
										to="/"
										class="text-sm lg:text-base text-[#000] font-medium"
									>
										Về chúng tôi
									</nuxt-link>
									<nuxt-link
										to="/"
										class="text-sm lg:text-base text-[#000] font-medium"
									>
										Tin UPS
									</nuxt-link>
									<nuxt-link
										to="/"
										class="text-sm lg:text-base text-[#000] font-medium"
									>
										Gia nhập UPS
									</nuxt-link>
								</div>
							</div>
						</div>

						<div class="mt-10 lg:mt-[75px]">
							<div class="flex gap-4 items-center">
								<p class="text-base lg:text-xl text-[#EEEEEE] font-normal">Tải ứng dụng</p>
								<i>
									<svg
										xmlns="http://www.w3.org/2000/svg"
										width="12"
										height="12"
										viewBox="0 0 12 12"
										fill="none"
									>
										<path
											d="M1.53033 0.46967C1.23744 0.176777 0.762563 0.176777 0.46967 0.46967C0.176777 0.762563 0.176777 1.23744 0.46967 1.53033L1.53033 0.46967ZM11 11.75C11.4142 11.75 11.75 11.4142 11.75 11L11.75 4.25C11.75 3.83579 11.4142 3.5 11 3.5C10.5858 3.5 10.25 3.83579 10.25 4.25V10.25H4.25C3.83579 10.25 3.5 10.5858 3.5 11C3.5 11.4142 3.83579 11.75 4.25 11.75L11 11.75ZM0.46967 1.53033L10.4697 11.5303L11.5303 10.4697L1.53033 0.46967L0.46967 1.53033Z"
											fill="#02E56A"
										/>
									</svg>
								</i>
							</div>

							<div class="mt-5 flex gap-4">
								<nuxt-link
									to="/"
									target="_blank"
									class="animate-ups__item h-[54px] lg:h-[68px] px-3 inline-flex gap-2 items-center rounded-[12px] bg-[#111111]"
								>
									<div class="inline-flex relative w-6 lg:w-8 h-6 lg:h-8">
										<nuxt-img
											format="webp"
											loading="lazy"
											alt="Google Play"
											width="32"
											height="32"
											src="/icons/chplay-icon.svg"
											class="absolute w-full h-full object-contain"
										/>
									</div>

									<div class="pr-0 lg:pr-5">
										<p class="text-[10px] lg:text-xs uppercase font-normal text-white opacity-55">
											Get it on
										</p>
										<p class="text-base lg:text-lg font-semibold text-white">Google Play</p>
									</div>
								</nuxt-link>

								<nuxt-link
									to="/"
									target="_blank"
									class="animate-ups__item h-[54px] lg:h-[68px] px-3 inline-flex gap-2 items-center rounded-[12px] bg-[#111111]"
								>
									<div class="inline-flex relative w-6 lg:w-8 h-6 lg:h-8">
										<nuxt-img
											format="webp"
											loading="lazy"
											alt="Google Play"
											width="32"
											height="32"
											src="/icons/app-store-icon.svg"
											class="absolute w-full h-full object-contain"
										/>
									</div>

									<div class="pr-0 lg:pr-5">
										<p class="text-[10px] lg:text-xs uppercase font-normal text-white opacity-55">
											Download on the
										</p>
										<p class="text-base lg:text-lg font-semibold text-white">App Store</p>
									</div>
								</nuxt-link>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- COPY RIGHT -->
		<div class="bg-[#15171E]">
			<div class="container">
				<div
					class="flex flex-col lg:flex-row items-center lg:items-start justify-center lg:justify-between py-[30px]"
				>
					<p class="text-sm text-white opacity-75">
						© 2024 <span class="text-green-ups">UP Securities</span>. All right reserved
					</p>

					<div class="flex flex-col lg:flex-row items-center mt-[10px] lg:mt-0 gap-[10px] lg:gap-6">
						<nuxt-link
							href="/"
							class="text-sm text-white opacity-75 font-medium"
						>
							Điều khoản & Quyền hạn
						</nuxt-link>
						<nuxt-link
							href="/"
							class="text-sm text-white opacity-75 font-medium"
						>
							Trung tâm hỗ trợ khách hàng
						</nuxt-link>
					</div>
				</div>
			</div>
		</div>
	</footer>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
	name: "the-footer",
	components: {},
	setup(props, ctx) {},
});
</script>

<style></style>

// src/components/common/the-footer/page.tsx
"use client";
import Link from "next/link";
import React from "react";
import NextImg from "../next-img";
import { useEffect } from "react";
import AOS from "aos";
import "aos/dist/aos.css";

type Props = {};

const TheFooter = (props: Props) => {
  useEffect(() => {
    AOS.init({ once: true });
  }, []);
  return (
    <div className="relative mt-10 bg-[#0F1B0E] text-[#FFF] lg:mt-[60px] xl:mt-20 2xl:mt-[160px]">
      <div className="custom-container pb-6 pt-10 md:py-10 lg2:pb-[52px] lg2:pt-[50px] xl:pt-[70px] 3xl:pb-[72px] 3xl:pt-[120px]">
        <div className="flex flex-col gap-10 lg:grid lg:grid-cols-[40%,60%] lg:gap-0 lg2:grid-cols-[45%,55%] 2xl:grid-cols-[50%,50%]">
          <div
            className="flex flex-col gap-4 md:grid md:grid-cols-2 md:gap-10 lg:flex lg:gap-4"
            data-aos="fade-up"
            data-aos-delay="200"
          >
            <span className="w-[90%] text-[20px] font-bold text-[#FFF] lg:w-[85%] lg:text-[24px] lg2:text-[40px] lg2:leading-[46px] 2xl:w-[70%] 2xl:text-[44px] 2xl:leading-[52px] 3xl:text-[48px] 3xl:leading-[56px]">
              <span className="text-[#02E56A]">
                Kiến tạo tương lai vẹn toàn
              </span>{" "}
              với nền tảng đầu tư đột phá
            </span>
            <p className="text-[14px] font-medium leading-[22px] text-[#8C9AA4] lg:w-[80%] lg:text-base lg:leading-[28px] lg2:text-[18px] 2xl:w-[70%]">
              UPS là công ty chứng khoán đột phá dành cho thế hệ mới, nơi công
              nghệ và tư duy đổi mới, sáng tạo hợp nhất để đem lại trải nghiệm
              đầu tư thông minh, dễ dàng, và thú vị.
            </p>
          </div>
          <div
            className="grid md:grid-cols-2 md:gap-10 lg:grid-cols-[auto,230px] lg:gap-[50px]"
            data-aos="fade-up"
            data-aos-delay="400"
          >
            <div className="flex flex-col">
              <p className="mb-3 border-b border-[#8C9AA4] pb-3 text-[14px] font-medium leading-[22px] text-[#8C9AA4] lg:mb-4 lg:pb-4 lg:text-base lg:leading-[28px] lg2:text-[18px]">
                UPS là công ty chứng khoán đột phá dành cho thế hệ mới, nơi công
                nghệ và tư duy đổi mới, sáng tạo hợp nhất để đem lại trải
              </p>
              <div className="flex flex-col gap-[6px]">
                <div className="flex items-center gap-[6px]">
                  <div className="relative h-[19px] w-[19px]">
                    <NextImg
                      src="/assets/icons/verify.svg"
                      alt="Capi"
                      objectFit="cover"
                      className=""
                    />
                  </div>
                  <p className="text-[14px] font-medium leading-[22px] text-[#8C9AA4] lg:text-base lg:leading-[28px] lg2:text-[18px]">
                    Trung tâm hỗ trợ thuận tiện
                  </p>
                </div>
                <div className="flex items-center gap-[6px]">
                  <div className="relative h-[19px] w-[19px]">
                    <NextImg
                      src="/assets/icons/verify.svg"
                      alt="Capi"
                      objectFit="cover"
                      className=""
                    />
                  </div>
                  <p className="text-[14px] font-medium leading-[22px] text-[#8C9AA4] lg:text-base lg:leading-[28px] lg2:text-[18px]">
                    Chuyên viên tư vấn chuyên nghiệp
                  </p>
                </div>
                <div className="flex items-center gap-[6px]">
                  <div className="relative h-[19px] w-[19px]">
                    <NextImg
                      src="/assets/icons/verify.svg"
                      alt="Capi"
                      objectFit="cover"
                      className=""
                    />
                  </div>
                  <p className="text-[14px] font-medium leading-[22px] text-[#8C9AA4] lg:text-base lg:leading-[28px] lg2:text-[18px]">
                    Phản hồi thông tin nhanh chóng
                  </p>
                </div>
              </div>
            </div>
            <div className="mt-10 md:mt-0">
              <button className="btn active">
                Mở tài khoản ngay
                <div className="relative h-4 w-4 lg:h-6 lg:w-6">
                  <NextImg
                    src="/assets/icons/UPs.svg"
                    alt="Capi"
                    objectFit="cover"
                  />
                </div>
              </button>
              <p className="mt-6 hidden text-[16px] font-medium leading-[24px] text-[#6E767C] md:block">
                Cảm ơn bạn đã tới với nền tảng giao dịch chứng khoán <br /> UP
                Securities
              </p>
            </div>
          </div>
        </div>
      </div>
      <div
        className="h-[1px] w-full bg-[#014227]"
        data-aos="fade-up"
        data-aos-delay="200"
      ></div>
      <div className="custom-container pb-10 pt-6 md:py-10 lg:pb-[50px] xl:py-[70px] 3xl:py-[120px]">
        <div className="gap-5 lg:grid lg:grid-cols-[25%,75%] xl:grid-cols-[32%,68%]">
          <div className="" data-aos="fade-up" data-aos-delay="200">
            <Link
              href="/"
              aria-label="Ups"
              title="Ups"
              className="inline-flex items-center"
            >
              <div className="relative h-10 w-[167px] rounded-br-2xl lg:h-[44px] lg:w-[184px]">
                <NextImg
                  src="/assets/icons/logo-ups.svg"
                  alt="Capi"
                  objectFit="cover"
                  className=""
                />
              </div>
            </Link>
          </div>
          <div
            className="flex flex-col gap-10 lg:gap-[70px]"
            data-aos="fade-up"
            data-aos-delay="400"
          >
            <div className="mt-10 grid grid-cols-2 gap-x-3 gap-y-6 lg:mt-0 lg:flex lg:justify-between">
              <div>
                <p className="text-[14px] font-bold leading-normal lg:text-base">
                  Khách hàng cá nhân
                </p>
                <ul className="mt-4 space-y-4 lg:mt-6 lg:space-y-6">
                  <li>
                    <div className="h-[1px] w-[10px] bg-[#02E56A]"></div>
                  </li>
                  <li>
                    <a
                      href="/"
                      className="text-[14px] font-medium leading-normal text-[#9BABB6] lg:text-base"
                    >
                      Ưu đãi
                    </a>
                  </li>
                  <li>
                    <a
                      href="/"
                      className="text-[14px] font-medium leading-normal text-[#9BABB6] lg:text-base"
                    >
                      Biểu phí giao dịch
                    </a>
                  </li>
                </ul>
              </div>
              <div>
                <p className="text-teal-accent-400 text-[14px] font-semibold lg:text-base">
                  Khách hàng doanh nghiệp
                </p>
                <ul className="mt-4 space-y-4 lg:mt-6 lg:space-y-6">
                  <li>
                    <div className="h-[1px] w-[10px] bg-[#02E56A]"></div>
                  </li>
                  <li>
                    <a
                      href="/"
                      className="text-[14px] font-medium leading-normal text-[#9BABB6] lg:text-base"
                    >
                      Tư vấn tài chính
                    </a>
                  </li>
                  <li>
                    <a
                      href="/"
                      className="text-[14px] font-medium leading-normal text-[#9BABB6] lg:text-base"
                    >
                      Tin đấu giá
                    </a>
                  </li>
                </ul>
              </div>
              <div>
                <p className="text-teal-accent-400 text-[14px] font-semibold lg:text-base">
                  Đầu tư cùng UPS
                </p>
                <ul className="mt-4 space-y-4 lg:mt-6 lg:space-y-6">
                  <li>
                    <div className="h-[1px] w-[10px] bg-[#02E56A]"></div>
                  </li>
                  <li>
                    <a
                      href="/"
                      className="text-[14px] font-medium leading-normal text-[#9BABB6] lg:text-base"
                    >
                      Nhận định thị trường
                    </a>
                  </li>
                  <li>
                    <a
                      href="/"
                      className="text-[14px] font-medium leading-normal text-[#9BABB6] lg:text-base"
                    >
                      Hướng dẫn sử dụng
                    </a>
                  </li>
                </ul>
              </div>
              <div>
                <p className="text-teal-accent-400 text-[14px] font-semibold lg:text-base">
                  Về UPS
                </p>
                <ul className="mt-4 space-y-4 lg:mt-6 lg:space-y-6">
                  <li>
                    <div className="h-[1px] w-[10px] bg-[#02E56A]"></div>
                  </li>
                  <li>
                    <a
                      href="/"
                      className="text-[14px] font-medium leading-normal text-[#9BABB6] lg:text-base"
                    >
                      Công bố thông tin
                    </a>
                  </li>
                  <li>
                    <a
                      href="/"
                      className="text-[14px] font-medium leading-normal text-[#9BABB6] lg:text-base"
                    >
                      Gia nhập UPS
                    </a>
                  </li>
                </ul>
              </div>
            </div>
            <div className="flex flex-wrap items-center gap-3">
              <div className="flex cursor-pointer items-center gap-[9px] rounded-[9px] bg-[#111] p-[10px] pr-8 lg:pr-[50px]">
                <div className="relative h-6 w-6">
                  <NextImg
                    src="/assets/icons/google-play1.svg"
                    alt="Capi"
                    objectFit="cover"
                  />
                </div>
                <div className="flex flex-col">
                  <span className="text-xs font-medium uppercase leading-normal text-[rgba(255,255,255,0.79)]">
                    Get it on
                  </span>
                  <span className="text-[14px] font-semibold leading-[21px] lg:text-base">
                    Google Play
                  </span>
                </div>
              </div>
              <div className="flex cursor-pointer items-center gap-[9px] rounded-[9px] bg-[#111] p-[10px] pr-6">
                <div className="relative h-6 w-6">
                  <NextImg
                    src="/assets/icons/apple-logo1.svg"
                    alt="Capi"
                    objectFit="cover"
                  />
                </div>
                <div className="flex flex-col">
                  <span className="text-xs font-medium uppercase leading-normal text-[rgba(255,255,255,0.79)]">
                    Download on the
                  </span>
                  <span className="text-[14px] font-semibold leading-[21px] lg:text-base">
                    App Store
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="bg-[#060B06]">
        <div className="custom-container flex flex-col items-center justify-between py-5 md:flex-row xl:py-[30px]">
          <p className="text-sm font-medium leading-normal text-[rgba(255,255,255,0.79)]">
            © 2024 <span className="text-[#02E56A]"> UP Securities</span>. All
            right reserved
          </p>
          <div className="mt-[14px] flex flex-col-reverse items-center gap-[14px] md:mt-0 md:flex-row lg:gap-6">
            <span className="text-sm font-medium leading-normal text-[rgba(255,255,255,0.79)]">
              Điều khoản & Quyền hạn
            </span>
            <span className="text-sm font-medium leading-normal text-[rgba(255,255,255,0.79)]">
              Trung tâm hỗ trợ khách hàng
            </span>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TheFooter;
